### ISSUE TITLE
Duda, sobre alcance del proyecto.

### ISSUE THREAD

**Issue by vapdl** [PanamediaSLU/Test#1]
Chicos buen Dia.

1.- Referente al proyecto, asumo se usa TDD por tal: el mismo trata de solo hacer las pruebas (unitarias, integracion) a lo solicitado? o despues de las pruebas generar una aplicacion para mostrar en pantalla (browser) el resultado del sorteo??.

2.- Puedo usar Laravel como Framework de desarrollo?.

Gracias.

**Comment by rmrbest** [comment]
hola @vapdl , la idea es hacer los test unitarios, integración, funcionales que creas conveniente. Si todo está cubierto no será necesario mostrarlo por pantalla. 

Sobre el framework de desarrollo, creo que no es necesario utilizar uno en concreto. Como indica el enunciado, el resultado puedes mostrarlo por el terminal cuando ejecutes el script.

Espero haberte aclarado las dudas.

Saludos,
